import os
from pathlib import Path
from dotenv import load_dotenv

project_root = Path(__file__).resolve().parent.parent
load_dotenv(project_root / '.env')

DATA_GENERATION_SEED = int(os.getenv('DATA_GENERATION_SEED', '44'))
CURRENT_EXPERIMENT = os.getenv("CURRENT_EXPERIMENT", "NYC")
CONFIG_FILEPATH = os.getenv("CONFIG_FILEPATH", "nyc_priority_config.json")

EXP_OUT_FOLDER = os.getenv('EXP_OUT_FOLDER', '')
RAW_DATA_DIR = os.getenv(
    'RAW_DATA_DIR',
    ''
)
POLISHED_DATA_DIR = os.getenv(
    'POLISHED_DATA_DIR',
    ''
)
CHILEAN_DATA_DIR = os.getenv(
    'CHILEAN_DATA_DIR',
    ''
)

MAIN_AGG_APP_STATS_FILEPATH = os.getenv("MAIN_AGG_APP_STATS_FILEPATH", "")

MAIN_AGG_MATCH_STATS_FILEPATH = os.getenv("MAIN_AGG_MATCH_STATS_FILEPATH", "")
MAIN_AGG_MATCH_STATS_FILEPATH_SHEET = os.getenv("MAIN_AGG_MATCH_STATS_FILEPATH_SHEET", "")

SCHOOL_INFO_STATS_FILEPATH = os.getenv("SCHOOL_INFO_STATS_FILEPATH", "")
SCHOOL_INFO_STATS_FILEPATH_SHEET = os.getenv("SCHOOL_INFO_STATS_FILEPATH_SHEET", "")

ADDTL_SCHOOL_INFO_STATS_FILEPATH = os.getenv("ADDTL_SCHOOL_INFO_STATS_FILEPATH", "")
ADDTL_SCHOOL_INFO_STATS_FILEPATH_SHEET = os.getenv("ADDTL_SCHOOL_INFO_STATS_FILEPATH_SHEET", "")

NYC_CONFIG_FILEPATH = os.getenv("NYC_CONFIG_FILEPATH", "")

CHILEAN_INDV_PREF_FILEPATH = os.getenv("CHILEAN_INDV_PREF_FILEPATH", "")
CHILEAN_MATCH_OUTCOME_FILEPATH = os.getenv("CHILEAN_MATCH_OUTCOME_FILEPATH", "")
CHILEAN_SCHOOL_CAPACITY_FILEPATH = os.getenv("CHILEAN_SCHOOL_CAPACITY_FILEPATH", "")
CHILEAN_SCHOOL_CAPACITY_BY_REGION_FILEPATH = os.getenv("CHILEAN_SCHOOL_CAPACITY_BY_REGION_FILEPATH", "")

CHILEAN_INDV_PREF_PROVINCE_FILEPATH = os.getenv("CHILEAN_INDV_PREF_PROVINCE_FILEPATH", "")
CHILEAN_MATCH_OUTCOME_PROVINCE_FILEPATH = os.getenv("CHILEAN_MATCH_OUTCOME_PROVINCE_FILEPATH", "")
CHILEAN_SCHOOL_CAPACITY_BY_REGION_PROVINCE_FILEPATH = os.getenv("CHILEAN_SCHOOL_CAPACITY_BY_REGION_PROVINCE_FILEPATH", "")


CHILE_CONFIG_FILEPATH = os.getenv("CHILE_CONFIG_FILEPATH", "")
